[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.149.1"
  HUGO_ENV = "production"
  NODE_VERSION = "18"

[[redirects]]
  from = "https://diagnosticpro.io/*"
  to = "https://jeremylongshore.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://jeremylongshore.com/*"
  to = "https://jeremylongshore.com/:splat"
  status = 301
  force = true